version: '3'
services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "4000:27017"
    restart: always
  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always